[[headers]]
for = "/ROMAIN_FAILLA_DEV_BACKEND_EN.pdf"
[headers.values]
content-disposition = 'attachment; filename="ROMAIN_FAILLA_DEV_BACKEND_EN.pdf"'

[[headers]]
for = "/ROMAIN_FAILLA_DEV_BACKEND_FR.pdf"
[headers.values]
content-disposition = 'attachment; filename="ROMAIN_FAILLA_DEV_BACKEND_FR.pdf"'
