name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Log into GitHub Container repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build an push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha }}
